// Product names and technology identifiers retain their original spelling.
export const arabic: Record<string, string> = {
  "B2B travel · Identity, payments & support": "حلول سفر للشركات — تسجيل الدخول والدفع والدعم",
  "Spring Boot & Laravel development": "تطوير باستخدام Spring Boot وLaravel",
  "Britrip is a B2B travel platform for agencies and businesses, bringing flights, hotels, and other travel services together. I developed its platform-wide SSO and payment systems with Spring Boot, plus a support and ticketing system with Laravel.": "Britrip منصة تجمع خدمات الطيران والفنادق وغيرها من خدمات السفر لوكالات السفر والشركات. طوّرت لها نظام تسجيل دخول موحّد ونظام مدفوعات باستخدام Spring Boot، إلى جانب نظام للدعم الفني وتذاكر الدعم باستخدام Laravel.",
  "Platform-wide SSO": "تسجيل دخول موحّد لكل الأنظمة",
  "Developed a shared single sign-on system for the whole platform. Kafka served as the central event hub, with WebSocket notifications delivering real-time updates.": "طوّرت نظام تسجيل دخول موحّد يخدم المنصة بأكملها، واعتمدت على Kafka كمحور مركزي لتبادل الأحداث بين الخدمات، مع إرسال الإشعارات لحظياً عبر WebSocket.",
  "Payment integrations": "ربط بوابات الدفع",
  "Developed the payment system and integrated Network International, Stripe, and Cryptomus to support the platform’s payment workflows.": "طوّرت نظام المدفوعات وربطته ببوابات Network International وStripe وCryptomus لتنفيذ عمليات الدفع داخل المنصة.",
  "Support & ticketing": "الدعم الفني وتذاكر الدعم",
  "Built the support and ticketing system in Laravel. Other Laravel backend developers connected their services to the shared SSO system.": "طوّرت نظام الدعم الفني وإدارة تذاكر الدعم باستخدام Laravel، وربط مطوّرو الخدمات الخلفية الأخرى المبنية على Laravel خدماتهم بنظام تسجيل الدخول الموحّد.",
  "Developed Britrip's platform-wide SSO and payment systems with Spring Boot, using Kafka as the central event hub and WebSocket for real-time notifications.": "طوّرت نظامَي تسجيل الدخول الموحّد والمدفوعات لمنصة Britrip باستخدام Spring Boot، مع Kafka لتبادل الأحداث بين الخدمات وWebSocket لإرسال الإشعارات لحظياً.",
  "Integrated Network International, Stripe, and Cryptomus into Britrip's payment system.": "ربطت نظام المدفوعات في Britrip ببوابات Network International وStripe وCryptomus.",
  "Built Britrip's support and ticketing system in Laravel; other Laravel backend developers connected their services to the shared SSO system.": "طوّرت نظام الدعم الفني وتذاكر الدعم في Britrip باستخدام Laravel، وربط مطوّرو الخدمات الخلفية الأخرى خدماتهم بنظام تسجيل الدخول الموحّد.",
  "Integrated payment providers": "بوابات الدفع التي ربطتها بالمنصة",
  "Pause animation": "إيقاف الحركة",
  "Resume animation": "تشغيل الحركة",
  "Charbel Mdawar": "شربل مدور",
  "Software Engineer": "مهندس برمجيات",
  "Damascus, Syria": "دمشق، سوريا",
  "Backend engineering with a quality-first mindset. I build secure services, connect real-time systems, and lead the testing that helps teams ship with confidence.": "أطوّر خدمات خلفية آمنة، وأربط الأنظمة التي تعمل في الوقت الفعلي، وأقود اختبارات الجودة لمساعدة الفرق على إطلاق برمجيات يمكن الاعتماد عليها.",
  "Building secure systems.": "أبني أنظمة آمنة.",
  "Delivering reliable software.": "وأقدّم برمجيات موثوقة.",
  "Quality Engineering": "هندسة الجودة",
  "Expertise": "المهارات",
  "Experience": "الخبرة",
  "Work": "المشاريع",
  "About": "نبذة عني",
  "Contact": "تواصل معي",
  "Let’s talk": "تواصل معي",
  "Skip to content": "انتقل إلى المحتوى",
  "Main navigation": "التنقل الرئيسي",
  "Charbel Mdawar home": "شربل مدور — الصفحة الرئيسية",
  "Close navigation menu": "إغلاق قائمة التنقل",
  "Open navigation menu": "فتح قائمة التنقل",
  "Explore my work": "اطّلع على مشاريعي",
  "Download CV": "تحميل السيرة الذاتية",
  "Explore expertise": "استكشف المهارات",
  "01 / Expertise": "01 / المهارات",
  "Built well.": "تطوير متقن.",
  "Tested thoroughly.": "واختبارات شاملة.",
  "Engineering and quality are part of the same process. Here is the toolkit I bring to both.": "بالنسبة لي، الجودة جزء من التطوير في كل خطوة. هذه أبرز المهارات والأدوات التي أستخدمها لبناء البرمجيات واختبارها.",
  "02 / Experience": "02 / الخبرة",
  "A foundation in quality.": "خبرة بدأت بضمان الجودة.",
  "A focus on engineering.": "وتوسّعت إلى تطوير الأنظمة.",
  "03 / Selected work": "03 / مشاريع مختارة",
  "From architecture": "من تصميم الأنظمة",
  "to application.": "إلى تطويرها واختبارها.",
  "Systems I have built and validated, spanning backend engineering, customer platforms, and quality assurance.": "أنظمة طوّرتها واختبرتها، تشمل الخدمات الخلفية ومنصات العملاء وضمان الجودة.",
  "More project details are included in the downloadable CV.": "للمزيد عن خبرتي ومشاريعي، يمكنك تحميل سيرتي الذاتية.",
  "Visit": "زيارة",
  "04 / About me": "04 / نبذة عني",
  "Curiosity in the code.": "شغف بالتعلّم والتطوير.",
  "Care in the details.": "واهتمام بأدق التفاصيل.",
  "Education": "التعليم",
  "Languages": "اللغات",
  "Community": "العمل التطوعي",
  "Bachelor of Computer Science": "بكالوريوس في علوم الحاسوب",
  "Damascus University": "جامعة دمشق",
  "Arabic": "العربية",
  "English": "الإنجليزية",
  "Volunteer": "متطوع",
  "RBCs Team": "فريق RBCs",
  "05 / Get in touch": "05 / تواصل معي",
  "Good software starts": "كل مشروع ناجح",
  "with a": "يبدأ",
  "conversation.": "بحوار.",
  "Have a project, an engineering challenge, or a role in mind? Let’s connect.": "لديك مشروع أو تحدٍ تقني أو فرصة عمل؟ يسعدني التواصل معك.",
  "References available on request.": "المراجع المهنية متاحة عند الطلب.",
  "Back to top": "العودة إلى الأعلى",
  "Backend development": "تطوير الأنظمة الخلفية",
  "Secure services and the business logic behind them.": "بناء خدمات آمنة تطبّق متطلبات العمل بدقة.",
  "Identity & integrations": "إدارة الهوية وربط الأنظمة",
  "Connected applications with thoughtful access control.": "ربط التطبيقات والخدمات مع ضبط صلاحيات الوصول لكل مستخدم.",
  "Payment gateways": "بوابات الدفع",
  "Quality engineering": "هندسة الجودة",
  "Test strategies that turn requirements into release confidence.": "خطط اختبار تغطّي المتطلبات وتتحقق من جاهزية البرمجيات للإطلاق.",
  "Test planning": "تخطيط الاختبارات",
  "Regression testing": "اختبار استقرار الوظائف بعد التحديث",
  "Performance & security": "الأداء والأمان",
  "Validation under load and across application attack surfaces.": "اختبار أداء التطبيقات تحت الضغط وفحص نقاط الضعف الأمنية.",
  "Access-control testing": "اختبار صلاحيات الوصول",
  "Data & messaging": "إدارة البيانات وتبادل الرسائل",
  "Persistence, caching, and asynchronous communication.": "تخزين البيانات والتخزين المؤقت والتواصل غير المتزامن.",
  "DevOps & delivery": "التطوير والتشغيل والإطلاق",
  "Reliable environments and practical production troubleshooting.": "تجهيز بيئات تشغيل مستقرة وتشخيص المشكلات بعد الإطلاق ومعالجتها.",
  "QA Manager": "مدير ضمان الجودة",
  "Dec 2025 — Present": "ديسمبر 2025 — حتى الآن",
  "Leading quality across web applications, APIs, and backend services.": "أقود ضمان الجودة لتطبيقات الويب وواجهات البرمجة والخدمات الخلفية.",
  "Lead manual, automated, performance, and security testing, with functional, integration, regression, and exploratory coverage.": "أقود الاختبارات اليدوية والآلية واختبارات الأداء والأمان، للتحقق من الوظائف وتكامل الأنظمة واستقرارها بعد التحديثات، إلى جانب الاختبارات الاستكشافية.",
  "Assess authentication, authorization, session management, and common OWASP risks; coordinate remediation with developers.": "أقيّم المصادقة والصلاحيات وإدارة الجلسات ومخاطر OWASP الشائعة، وأنسق مع المطورين لمعالجتها.",
  "Validate reliability under load and communicate risks and release readiness to stakeholders.": "أتحقق من الموثوقية تحت الضغط وأوضح المخاطر وجاهزية الإصدارات لأصحاب المصلحة.",
  "QA leadership": "قيادة ضمان الجودة",
  "Test strategy": "استراتيجية الاختبار",
  "Security testing": "اختبار الأمان",
  "Performance testing": "اختبار الأداء",
  "Java Spring Developer / Team Lead": "مطور Java Spring / قائد فريق",
  "Jan 2025 — Nov 2025": "يناير 2025 — نوفمبر 2025",
  "Building enterprise identity and payment services with Java and Spring Boot.": "تطوير خدمات الهوية والدفع للمؤسسات باستخدام Java وSpring Boot.",
  "Led a centralized SSO platform with Java 21, Spring Boot, Spring Security, OAuth 2.0, SAML, and JWT.": "قدت تطوير منصة موحدة لتسجيل الدخول باستخدام Java 21 وSpring Boot وSpring Security وOAuth 2.0 وSAML وJWT.",
  "Designed secure APIs and identity workflows covering roles, OTP, device trust, and audit-focused controls.": "صممت واجهات برمجة آمنة ومسارات لإدارة الهوية تشمل الأدوار ورموز التحقق والثقة بالأجهزة وضوابط التدقيق.",
  "Architected gateway integrations for checkout, capture, webhooks, and payment links with resilient error handling.": "صممت تكاملات بوابات الدفع لإتمام الشراء وتحصيل المدفوعات والإشعارات الآلية وروابط الدفع، مع معالجة مرنة للأخطاء.",
  "Supported Oracle, Kafka events, WebSocket notifications, CI/CD, and Linux production troubleshooting.": "دعمت Oracle وأحداث Kafka وإشعارات WebSocket والتكامل والنشر المستمرين، وعالجت مشكلات الإنتاج على Linux.",
  "Laravel Developer": "مطور Laravel",
  "May 2024 — Nov 2025": "مايو 2024 — نوفمبر 2025",
  "Delivering real-time applications and improving performance across the stack.": "تطوير تطبيقات تعمل في الوقت الفعلي وتحسين أدائها على مستوى الواجهات والخدمات وقواعد البيانات.",
  "Developed Laravel applications and reusable Blade components with WebSockets and Laravel Reverb.": "طوّرت تطبيقات Laravel ومكونات Blade قابلة لإعادة الاستخدام مع WebSockets وLaravel Reverb.",
  "Maintained Nginx, SSL/TLS, caching headers, and deployment environments.": "أدرت Nginx وSSL/TLS وترويسات التخزين المؤقت وبيئات النشر.",
  "Improved performance through query optimization, Redis caching, profiling, and targeted refactoring.": "حسّنت الأداء عبر تحسين الاستعلامات والتخزين المؤقت باستخدام Redis وتحليل الأداء وإعادة هيكلة أجزاء محددة من الشيفرة.",
  "Built PHPUnit and k6 tests to validate code quality and behavior under load.": "أنشأت اختبارات باستخدام PHPUnit وk6 للتحقق من جودة الشيفرة وسلوك النظام تحت الضغط.",
  "Quality Assurance Specialist": "أخصائي ضمان الجودة",
  "Mar 2023 — Apr 2024": "مارس 2023 — أبريل 2024",
  "Validating APIs and web interfaces from business rules to security.": "التحقق من واجهات البرمجة والويب، من قواعد الأعمال إلى الأمان.",
  "Tested REST APIs with Postman for data integrity, business rules, error handling, and database integration.": "اختبرت واجهات REST باستخدام Postman للتحقق من سلامة البيانات وقواعد الأعمال ومعالجة الأخطاء والتكامل مع قواعد البيانات.",
  "Performed functional, responsive, cross-browser, and form-validation testing.": "أجريت اختبارات وظيفية واختبارات التجاوب والتوافق بين المتصفحات والتحقق من النماذج.",
  "Conducted baseline security tests with OWASP ZAP and manual techniques; documented reproducible defects and verified fixes.": "أجريت اختبارات أمان أساسية باستخدام OWASP ZAP وأساليب يدوية، ووثقت العيوب القابلة لإعادة الإنتاج وتحققت من إصلاحها.",
  "API testing": "اختبار واجهات البرمجة",
  "Multi-tenant SaaS call center platform": "منصة سحابية لمراكز الاتصال تخدم مؤسسات متعددة",
  "In active development": "قيد التطوير",
  "A call center platform connecting real-time calling with the customer and organizational workflows behind every conversation.": "منصة لمراكز الاتصال تجمع المكالمات المباشرة وإدارة بيانات العملاء وتنظيم العمل في نظام متكامل.",
  "Real-time calling": "المكالمات المباشرة",
  "Spring Boot, LiveKit, and WebRTC power calling, IVR flows, DTMF handling, and live queues. WebSocket/STOMP handles signaling; Firebase Cloud Messaging notifies offline agents.": "تدعم Spring Boot وLiveKit وWebRTC المكالمات والرد الصوتي التفاعلي وإشارات DTMF وطوابير الانتظار. يتولى WebSocket/STOMP الإشارات، وتنبّه Firebase Cloud Messaging الوكلاء غير المتصلين.",
  "Business operations": "عمليات الأعمال",
  "A separate core backend manages tenants, users, roles, presence, CRM, and HR. Customer timelines automatically capture call activity.": "يدير نظام خلفي أساسي مستقل المؤسسات والمستخدمين والأدوار وحالة التواجد وعلاقات العملاء والموارد البشرية. ويسجل السجل الزمني للعملاء نشاط المكالمات تلقائياً.",
  "Connected architecture": "بنية مترابطة",
  "Oracle stores business data, RabbitMQ carries asynchronous events, and Redis supports hot-path data. A Python LiveKit Agent integrates ElevenLabs text-to-speech.": "تخزّن Oracle بيانات الأعمال، وتنقل RabbitMQ الأحداث غير المتزامنة، وتدعم Redis البيانات كثيرة الاستخدام. ويتكامل وكيل LiveKit مكتوب بلغة Python مع ElevenLabs لتحويل النص إلى كلام.",
  "Brag CRM": "البرق المضيء — إدارة علاقات العملاء",
  "Customer relationship management": "إدارة علاقات العملاء",
  "CRM project": "مشروع إدارة علاقات العملاء",
  "A CRM project for Al-Barq Al-Mudee, a Saudi telecommunications retailer offering smart devices, installment programs, and after-sales services.": "مشروع لإدارة علاقات العملاء لمؤسسة البرق المضيء السعودية للاتصالات، التي تقدم الأجهزة الذكية وبرامج التقسيط وخدمات ما بعد البيع.",
  "Digital storefront": "واجهة متجر رقمية",
  "Built around a catalog of phones, smartwatches, gaming devices, and accessories with product-led browsing.": "كتالوج يتيح تصفح الهواتف والساعات الذكية وأجهزة الألعاب والإكسسوارات والاطّلاع على تفاصيلها.",
  "Flexible financing": "تمويل مرن",
  "Presents installment programs designed to make current devices accessible without an upfront payment.": "عرض برامج تقسيط تتيح اقتناء الأجهزة الحديثة دون دفعة أولى.",
  "Customer experience": "تجربة العملاء",
  "Connects product discovery with support, warranty, maintenance, and direct customer contact.": "ربط استكشاف المنتجات بالدعم والضمان والصيانة والتواصل المباشر مع العملاء.",
  "Telecommunications": "الاتصالات",
  "Device retail": "تجارة الأجهزة",
  "Customer support": "دعم العملاء",
  "Al-Ahlam ERP & Manufacturing System": "الأحلام — نظام تخطيط الموارد والتصنيع",
  "Food production & enterprise operations": "إنتاج الأغذية وعمليات المؤسسات",
  "Quality assurance": "ضمان الجودة",
  "Al-Ahlam is a Syrian food manufacturer and exporter established in 1974. Its ERP and manufacturing system supports the business and production workflows behind a broad range of food products.": "الأحلام شركة سورية لتصنيع وتصدير الأغذية تأسست عام 1974. يدعم نظام تخطيط الموارد والتصنيع فيها مسارات الأعمال والإنتاج لمجموعة واسعة من المنتجات الغذائية.",
  "End-to-end validation": "اختبار دورة العمل كاملة",
  "Led validation of ERP and manufacturing workflows for a large food producer.": "قدت التحقق من مسارات عمل تخطيط الموارد والتصنيع لدى شركة كبيرة لإنتاج الأغذية.",
  "Business-rule coverage": "تغطية قواعد الأعمال",
  "Focused on business rules across enterprise and production processes.": "ركزت على قواعد الأعمال عبر عمليات المؤسسة والإنتاج.",
  "Data integrity": "سلامة البيانات",
  "Validated data integrity to reduce operational risk.": "تحققت من سلامة البيانات لتقليل المخاطر التشغيلية.",
  "Manufacturing": "التصنيع",
  "Business-rule testing": "اختبار قواعد الأعمال",
  "Salaza ERP, CRM & HR": "سالازا — تخطيط الموارد والعملاء والموارد البشرية",
  "Multi-branch salon operations": "إدارة صالونات متعددة الفروع",
  "Salaza Group provides hair, beauty, nail, and bridal services through 16 salons across Syria, the UAE, and Iraq. The project covers enterprise, customer, and workforce operations across branches.": "تقدم مجموعة سالازا خدمات الشعر والتجميل والأظافر والعرائس عبر 16 صالوناً في سوريا والإمارات والعراق. يغطي المشروع عمليات المؤسسة والعملاء والموظفين عبر الفروع.",
  "Validated multi-branch business workflows across the ERP system.": "تحققت من مسارات الأعمال متعددة الفروع ضمن نظام تخطيط الموارد.",
  "Customers & workforce": "العملاء والموظفون",
  "Tested customer-management and HR workflows supporting salon operations.": "اختبرت مسارات إدارة العملاء والموارد البشرية الداعمة لعمليات الصالونات.",
  "Release confidence": "جاهزية الإطلاق",
  "Improved release confidence across a network of 16 salons in three countries.": "ساهمت في رفع موثوقية الإصدارات وجاهزيتها للاستخدام في 16 صالوناً موزعة على ثلاث دول.",
  "Multi-branch testing": "اختبار تعدد الفروع",
  "El-Salleh E-Commerce": "السلة — التجارة الإلكترونية",
  "Everyday shopping & grocery delivery": "التسوق اليومي وتوصيل البقالة",
  "El-Salleh is a Syrian shopping and delivery platform connecting households with everyday essentials through a digital catalog and home delivery.": "السلة منصة سورية للتسوق والتوصيل تتيح للأسر الحصول على احتياجاتها اليومية عبر كتالوج رقمي وخدمة توصيل إلى المنزل.",
  "Shopping journeys": "تجربة التسوق",
  "Tested catalog browsing, cart behavior, and ordering journeys.": "اختبرت تجربة التسوق من تصفح المنتجات وإضافتها إلى السلة حتى إتمام الطلب.",
  "Coverage & delivery": "التغطية والتوصيل",
  "Validated store coverage and delivery journeys across the shopping experience.": "تحققت من مناطق خدمة المتاجر وخطوات توصيل الطلبات ضمن تجربة التسوق.",
  "Order accuracy": "دقة الطلبات",
  "Focused on protecting order accuracy and providing a more reliable grocery-shopping experience.": "ركزت على ضمان دقة الطلبات وتقديم تجربة أكثر موثوقية لتسوق البقالة.",
  "E-commerce": "التجارة الإلكترونية",
  "Cart & checkout": "السلة وإتمام الشراء",
  "Delivery": "التوصيل",
  "Journey testing": "اختبار تجربة المستخدم",
  "Children’s activities & family experiences": "أنشطة الأطفال وتجارب العائلات",
  "GoPal helps families in Saudi Arabia discover and book sports, arts, and educational activities. Child assessments guide recommendations, while STC Qitaf integration enables loyalty-point bookings.": "تساعد GoPal العائلات في السعودية على اكتشاف الأنشطة الرياضية والفنية والتعليمية وحجزها. توجّه تقييمات الأطفال التوصيات، ويتيح التكامل مع قطاف STC الحجز باستخدام نقاط الولاء.",
  "Family journeys": "تجربة العائلات",
  "Validated child profiles, activity discovery, and booking workflows.": "تحققت من ملفات الأطفال واستكشاف الأنشطة ومسارات الحجز.",
  "Provider operations": "إدارة مراكز الأنشطة",
  "Tested provider workflows to strengthen reliability for activity centers.": "اختبرت إجراءات العمل الخاصة بمقدمي الأنشطة لضمان عمل النظام بشكل موثوق لدى المراكز.",
  "Assessments & loyalty": "التقييمات وبرامج المكافآت",
  "Validated assessment outputs and loyalty integration for a dependable family experience.": "تحققت من نتائج التقييمات وربط برامج المكافآت بالتطبيق، لضمان تجربة موثوقة للعائلات.",
  "Activity booking": "حجز الأنشطة",
  "Child profiles": "ملفات الأطفال",
  "Assessments": "التقييمات",
  "Loyalty integration": "ربط برامج المكافآت",
  "Smo Al Mosafer": "سمو المسافر",
  "Transport booking & service requests": "حجز النقل وطلبات الخدمة",
  "A transport booking and service-request platform connecting customer trip journeys with operational workflows.": "منصة لحجز الرحلات وطلب خدمات النقل، تربط طلبات العملاء بإجراءات العمل لدى فريق التشغيل.",
  "Transport booking": "حجز النقل",
  "Tested booking journeys and trip creation across customer-facing features.": "اختبرت خطوات الحجز وإنشاء الرحلات من خلال الواجهات التي يستخدمها العملاء.",
  "Service requests": "طلبات الخدمة",
  "Validated service-request journeys across customer and operational workflows.": "اختبرت دورة طلب الخدمة من تقديم العميل للطلب إلى متابعته من فريق التشغيل.",
  "Release reliability": "موثوقية الإصدارات",
  "Focused on reducing release risk in trip creation and customer-facing features.": "ركزت على تقليل احتمالات ظهور أخطاء بعد الإطلاق في إنشاء الرحلات والميزات التي يستخدمها العملاء.",
  "Transport": "النقل",
  "Booking": "الحجز",
  "Workflow validation": "التحقق من مسارات العمل",
  "Crypto trading platform": "منصة تداول العملات الرقمية",
  "May 2025 — Mar 2026": "مايو 2025 — مارس 2026",
  "A Laravel application bringing the platform backend, customer workflows, and web interface together.": "تطبيق Laravel يجمع النظام الخلفي للمنصة ومسارات عمل العملاء وواجهة الويب.",
  "Application development": "تطوير التطبيق",
  "Developed the backend with Laravel and built the web interface using reusable Blade templates.": "طوّرت النظام الخلفي باستخدام Laravel وواجهة الويب باستخدام قوالب Blade قابلة لإعادة الاستخدام.",
  "Crypto payments": "الدفع بالعملات الرقمية",
  "Integrated a cryptocurrency payment method to support payment workflows within the platform.": "دمجت وسيلة دفع بالعملات الرقمية لدعم مسارات الدفع داخل المنصة.",
  "Customer management": "إدارة العملاء",
  "Implemented CRM functionality to organize customer information and related business activities.": "نفذت وظائف إدارة علاقات العملاء لتنظيم معلومات العملاء وأنشطة الأعمال المرتبطة بهم.",
  "Crypto payment integration": "تكامل الدفع بالعملات الرقمية",
  "Two backends. Clear responsibilities.": "نظامان خلفيان. مسؤوليات واضحة.",
  "Calling backend": "نظام الاتصالات الخلفي",
  "Core backend": "النظام الخلفي الأساسي",
  "IVR & call queues": "الرد الصوتي وطوابير المكالمات",
  "Users & tenants": "المستخدمون والمؤسسات",
  "Roles & presence": "الأدوار وحالة التواجد",
  "CRM & HR": "العملاء والموارد البشرية",
  "Shared service-token contract": "عقد مشترك لرمز مصادقة الخدمات",
  "Oracle · persistence": "Oracle · تخزين البيانات",
  "RabbitMQ · events": "RabbitMQ · الأحداث",
  "Redis · hot-path data": "Redis · البيانات كثيرة الاستخدام",
  "My experience spans both building software and validating it. From testing APIs and web interfaces to leading authentication, payment, and quality initiatives, I bring a practical understanding of how systems behave beyond the happy path.": "جمعت في عملي بين تطوير البرمجيات واختبارها؛ من فحص واجهات الويب وواجهات البرمجة إلى قيادة مشاريع تسجيل الدخول والدفع وضمان الجودة. علّمتني هذه التجربة كيف تعمل الأنظمة في الاستخدام اليومي، وكيف تتصرف عند حدوث خطأ أو موقف غير متوقع.",
  "I work across backend services, application security, performance, and delivery—collaborating with developers and stakeholders to make software more reliable from development through release.": "أهتم بتطوير الخدمات الخلفية وأمان التطبيقات وتحسين الأداء، وأتعاون مع المطورين وفرق العمل لبناء برمجيات موثوقة ومتابعتها من أولى مراحل التطوير حتى الإطلاق.",
};
