const c = (en: string, ar: string) => ({ en, ar });
export const projectSlugs = ["callx", "britrip", "brag-crm", "al-ahlam-erp", "salaza", "el-salleh", "gopal", "smo-al-mosafer", "cryptox"];
export const caseStudies: Record<string, { title?: ReturnType<typeof c>; sections: ReturnType<typeof c>[][]; posts: string[] }> = {
 callx: { title: c("CallX: Multi-Tenant Contact Center with Spring Boot, LiveKit & WebRTC", "CallX: مركز اتصال متعدد المؤسسات باستخدام Spring Boot وLiveKit وWebRTC"), sections: [
 [c("Problem and requirements", "المشكلة والمتطلبات"), c("CallX connects live conversations with the organizational workflows behind them. The documented scope includes tenants, agent presence, IVR, DTMF, queues, CRM, and HR. Keeping a call responsive and keeping a customer record correct are related goals, but they involve different workloads. The platform is in active development; this case study describes the implemented scope rather than a finished production rollout.", "يربط CallX المحادثات المباشرة بعمليات المؤسسات خلفها. يشمل النطاق المؤسسات وحضور الموظفين وIVR وDTMF والطوابير وCRM والموارد البشرية. ترتبط استجابة المكالمة بصحة سجل العميل لكنهما يتطلبان أعباء مختلفة. المنصة قيد التطوير؛ وتصف هذه الدراسة النطاق المنفذ لا إطلاقاً إنتاجياً مكتملاً.")],
 [c("Calling backend and media", "خدمة المكالمات والوسائط"), c("I built the calling backend with Spring Boot, LiveKit, WebRTC, and WebSocket/STOMP. It covers IVR flows, DTMF handling, and live queues; Firebase Cloud Messaging notifies offline agents. A Python LiveKit Agent worker integrates ElevenLabs text-to-speech. The distinction between media transport, application signaling, and offline notification makes each responsibility visible in the architecture.", "بنيت خدمة المكالمات باستخدام Spring Boot وLiveKit وWebRTC وWebSocket/STOMP. تشمل IVR وDTMF والطوابير المباشرة، مع Firebase Cloud Messaging لإشعار الموظفين غير المتصلين. يدمج عامل Python LiveKit Agent تحويل النص إلى كلام عبر ElevenLabs. يوضح فصل نقل الوسائط وإشارات التطبيق والإشعارات مسؤولية كل جزء.")],
 [c("Core backend and customer context", "الخدمة الأساسية وسياق العميل"), c("The core backend manages users, tenants, roles, presence, CRM, and HR. CRM capabilities include customers, contacts, campaigns, pipelines, leads, opportunities, and interactions. Automatic call logging connects conversations to customer timelines, so call activity becomes part of the business record rather than remaining isolated in the calling system.", "تدير الخدمة الأساسية المستخدمين والمؤسسات والأدوار والحضور وCRM والموارد البشرية. تشمل إدارة العملاء جهات الاتصال والحملات ومسارات البيع والعملاء المحتملين والفرص والتفاعلات. يربط تسجيل المكالمات الآلي المحادثات بالسجل الزمني للعميل، لتصبح جزءاً من سجل الأعمال بدلاً من بقائها معزولة في نظام الاتصال.")],
 [c("Persistence, events, and hot-path data", "التخزين والأحداث والبيانات كثيرة الاستخدام"), c("Oracle provides persistence, RabbitMQ carries asynchronous events, and Redis supports hot-path data. The two backends communicate through a shared service-token contract. This design separates responsibilities without removing the need for clear cross-service contracts. LDAP/Active Directory, SAML 2.0, OAuth 2.0/OIDC, SaaS, and self-hosted deployment patterns are documented in the project work.", "توفر Oracle التخزين الدائم، وينقل RabbitMQ الأحداث غير المتزامنة، ويدعم Redis البيانات كثيرة الاستخدام. تتواصل الخدمتان عبر عقد مشترك لرموز الخدمة. يفصل التصميم المسؤوليات مع الحفاظ على ضرورة عقود واضحة بين الخدمات. يشمل العمل توثيق أنماط LDAP وActive Directory وSAML وOAuth/OIDC وSaaS والاستضافة الذاتية.")],
 [c("Failure handling: review boundaries", "التعامل مع الفشل: حدود المراجعة"), c("A useful review of this architecture asks what happens when an agent disconnects, a notification arrives late, or a business event is repeated. Media reconnection, durable call records, and presence reconciliation need separate acceptance criteria. These are engineering review scenarios; the available project record does not establish measured recovery times or a specific retry policy.", "تسأل المراجعة المفيدة عما يحدث عند انقطاع الموظف أو تأخر الإشعار أو تكرار حدث أعمال. تحتاج إعادة اتصال الوسائط وسجلات المكالمات الدائمة ومطابقة الحضور إلى معايير قبول منفصلة. هذه سيناريوهات مراجعة هندسية؛ ولا يتضمن سجل المشروع قياسات لوقت التعافي أو سياسة محددة لإعادة المحاولة.")],
 [c("Delivered capability and design takeaway", "القدرات المنفذة والخلاصة التصميمية"), c("The documented result is a platform that combines real-time calling, organizational management, and CRM call history in separate cooperating services. The architectural takeaway is to give latency-sensitive communication and durable business operations explicit boundaries. No throughput, availability, or response-time figures are claimed here.", "النتيجة الموثقة منصة تجمع الاتصال اللحظي وإدارة المؤسسات وسجل مكالمات العملاء في خدمات منفصلة ومتعاونة. الخلاصة التصميمية هي وضع حدود واضحة بين الاتصالات الحساسة للتأخير وعمليات الأعمال الدائمة. لا تتضمن الدراسة ادعاءات رقمية عن السعة أو التوافر أو زمن الاستجابة.")]
 ], posts: ["real-time-systems-and-recovery", "designing-reliable-api-contracts", "centralized-sso-enterprise-applications"] },
 britrip: { title: c("Britrip: Spring Boot SSO, Payment Integrations & Laravel Support", "Britrip: الدخول الموحد والدفع عبر Spring Boot والدعم عبر Laravel"), sections: [
 [c("One platform, connected responsibilities", "منصة واحدة ومسؤوليات مترابطة"), c("Britrip is a B2B travel platform bringing flights, hotels, and related services together. My contribution covered platform-wide SSO and payment systems in Spring Boot, plus support and ticketing in Laravel. Other Laravel backend developers connected their services to the shared SSO, making the integration contract important across the team.", "Britrip منصة سفر للأعمال تجمع الرحلات والفنادق والخدمات المرتبطة. شملت مساهمتي الدخول الموحد والدفع عبر Spring Boot والدعم والتذاكر عبر Laravel. ربط مطورو Laravel الآخرون خدماتهم بالدخول الموحد، ما جعل عقد التكامل مهماً للفريق بأكمله.")],
 [c("Identity and event-driven integration", "الهوية والتكامل القائم على الأحداث"), c("The shared SSO connects applications around a common identity service. Kafka serves as the central event hub, and WebSocket notifications deliver real-time updates. Identity decisions, durable business events, and user-facing notifications are distinct concerns even when they participate in the same workflow.", "يربط الدخول الموحد التطبيقات بخدمة هوية مشتركة. يعمل Kafka كمحور للأحداث وتوفر إشعارات WebSocket التحديثات اللحظية. قرارات الهوية وأحداث الأعمال الدائمة والإشعارات للمستخدم مسؤوليات مختلفة حتى عندما تشارك في مسار واحد.")],
 [c("Payments and support", "المدفوعات والدعم"), c("I developed payment integrations with Network International, Stripe, and Cryptomus. The broader payment-service work covered checkout, capture, webhooks, payment links, validation, and resilient error handling. The Laravel support and ticketing system provides a separate operational capability alongside those services.", "طورت تكاملات الدفع مع Network International وStripe وCryptomus. شمل العمل في خدمات الدفع الإتمام والتحصيل وإشعارات webhooks وروابط الدفع والتحقق ومعالجة الأخطاء بمرونة. يوفر نظام الدعم والتذاكر عبر Laravel قدرة تشغيلية مستقلة إلى جانب تلك الخدمات.")],
 [c("Result and integration lesson", "النتيجة ودرس التكامل"), c("The delivered scope gives the platform shared sign-in, multiple payment integrations, and a dedicated support workflow. A useful design lesson is to keep provider-specific behavior behind clear application contracts, so payment notifications and support actions do not become responsible for identity policy. Quantitative conversion or reliability improvements are not documented.", "يوفر النطاق المنفذ دخولاً مشتركاً وتكاملات دفع متعددة ومسار دعم مخصصاً. من الدروس التصميمية المفيدة إبقاء سلوك كل مزود خلف عقود واضحة للتطبيق، كي لا تصبح إشعارات الدفع وإجراءات الدعم مسؤولة عن سياسة الهوية. لا تتوفر نتائج رقمية موثقة للتحويل أو الموثوقية.")]
 ], posts: ["centralized-sso-enterprise-applications", "payment-integrations-state-transitions", "real-time-systems-and-recovery"] },
 "al-ahlam-erp": { sections: [
 [c("Validation scope", "نطاق التحقق"), c("I led end-to-end validation of ERP and manufacturing workflows for Al-Ahlam. The focus was business-rule coverage and data integrity across enterprise and production processes. Testing this kind of system requires following records across a workflow rather than treating each screen as an isolated feature.", "قدت التحقق الشامل من مسارات ERP والتصنيع للأحلام، مع التركيز على قواعد العمل وسلامة البيانات عبر العمليات الإدارية والإنتاجية. يتطلب هذا النوع من الاختبار تتبع السجلات خلال المسار بدلاً من التعامل مع كل شاشة كميزة معزولة.")],
 [c("Operational outcome", "النتيجة التشغيلية"), c("The QA contribution focused on reducing operational risk by validating complete workflows and their underlying data. The project demonstrates the connection between business requirements and testable invariants. Detailed defect counts and measured reductions in production incidents are not available in the supplied experience record.", "ركزت مساهمة الجودة على تقليل المخاطر التشغيلية بالتحقق من المسارات الكاملة وبياناتها. يوضح المشروع العلاقة بين متطلبات العمل والقواعد القابلة للاختبار. لا يتضمن سجل الخبرة أعداداً تفصيلية للعيوب أو انخفاضاً مقاساً في حوادث الإنتاج.")]
 ], posts: ["erp-testing-business-rules-data-integrity", "testing-beyond-the-happy-path", "qa-leadership-release-readiness"] },
 salaza: { sections: [
 [c("Multi-branch scope", "نطاق متعدد الفروع"), c("My validation work covered ERP, CRM, and HR workflows supporting 16 salons across Syria, the UAE, and Iraq. The scope spans business operations, customer management, and workforce processes. Branch context matters because records and actions can have different visibility and ownership across an organization.", "شمل عملي التحقق من مسارات ERP وCRM والموارد البشرية التي تدعم 16 صالوناً في سوريا والإمارات والعراق. يغطي النطاق العمليات وإدارة العملاء والموظفين. يهم سياق الفرع لاختلاف ظهور السجلات وملكيتها داخل المؤسسة.")],
 [c("Release confidence across workflows", "الثقة بالإصدار عبر المسارات"), c("The documented contribution is improved release confidence across branch operations through workflow validation. It does not establish a measured percentage reduction in defects. The practical testing perspective is to connect customer and workforce journeys to their business rules, then report remaining risks with enough context for release decisions.", "المساهمة الموثقة هي تحسين الثقة بالإصدار عبر عمليات الفروع من خلال التحقق من المسارات، دون نسبة مقاسة لانخفاض العيوب. المنظور العملي هو ربط رحلات العملاء والموظفين بقواعد العمل، ثم توضيح المخاطر المتبقية بسياق يدعم قرار الإصدار.")]
 ], posts: ["erp-testing-business-rules-data-integrity", "qa-leadership-release-readiness"] },
};
export function relatedPostSlugs(slug: string) {
 return caseStudies[slug]?.posts ?? (slug === "cryptox" ? ["laravel-performance-measure-before-caching", "payment-integrations-state-transitions"] : ["testing-beyond-the-happy-path", "designing-reliable-api-contracts", "qa-leadership-release-readiness"]);
}
