const c = (en: string, ar: string) => ({ en, ar });
export const deepDives: Record<string, { title: ReturnType<typeof c>; sections: ReturnType<typeof c>[][]; flow: ReturnType<typeof c>[]; references: { title: string; url: string }[] }> = {
 "centralized-sso-enterprise-applications": {
 title: c("Building Centralized SSO with Spring Boot: OAuth 2.0, SAML, JWT & RBAC", "بناء الدخول الموحد باستخدام Spring Boot: OAuth 2.0 وSAML وJWT والأدوار"),
 flow: [c("Application / sign-in", "التطبيق / تسجيل الدخول"), c("Identity provider", "مزود الهوية"), c("Validated identity", "هوية متحقق منها"), c("Service authorization", "تفويض الخدمة")],
 sections: [
 [c("An authentication flow with explicit trust boundaries", "مسار مصادقة بحدود ثقة واضحة"), c("For an illustrative browser flow, the application redirects the user to an identity provider, the provider authenticates the user, and the application processes the protocol response before establishing its session. The diagram is a conceptual boundary map, not the exact production topology. Keep the browser, application, identity provider, and downstream APIs distinct when reviewing where credentials are accepted and where authorization happens.", "في مسار متصفح توضيحي، يحول التطبيق المستخدم إلى مزود الهوية الذي يصادق عليه، ثم يعالج التطبيق استجابة البروتوكول قبل إنشاء الجلسة. يوضح الرسم حدوداً مفاهيمية لا البنية الإنتاجية الدقيقة. افصل المتصفح والتطبيق ومزود الهوية والواجهات اللاحقة عند مراجعة قبول بيانات الاعتماد ومكان التفويض.")],
 [c("JWT validation and resource ownership", "التحقق من JWT وملكية الموارد"), c("A token’s presence is not proof that a request is authorized. A Spring Security resource server can validate JWT signatures and issuer and time claims; audience validation should match the intended API. The application must still enforce resource ownership and tenant scope. A valid token for a user in one organization does not by itself permit reading another organization’s customer record. Document these checks as separate layers.", "وجود الرمز لا يثبت السماح بالطلب. يستطيع خادم الموارد في Spring Security التحقق من توقيع JWT والمصدر والمدة، ويجب أن يطابق الجمهور الواجهة المقصودة. يبقى على التطبيق فرض ملكية الموارد ونطاق المؤسسة. لا يسمح رمز صالح لمستخدم في مؤسسة بقراءة سجل عميل في مؤسسة أخرى تلقائياً. وثّق هذه الفحوصات كطبقات منفصلة.")],
 [c("Token lifetime, refresh, and access changes", "مدة الرمز والتجديد وتغييرات الوصول"), c("Treat token lifetime as a design decision with operational consequences. Short access-token lifetimes reduce the period in which an old authorization snapshot remains usable, but they make renewal behavior more important. A refresh token belongs at the authorization boundary, not as a credential sent to every business API. Define what happens when a role is removed or an account is disabled, including how soon existing sessions stop working. Do not assume that changing a database row instantly invalidates every previously issued token.", "تعامل مع مدة الرمز كقرار تصميمي له آثار تشغيلية. تقلل المدة القصيرة فترة استخدام صلاحيات قديمة لكنها تزيد أهمية التجديد. ينتمي رمز التجديد إلى حدود التفويض وليس كاعتماد يرسل لكل واجهة أعمال. حدد أثر إزالة دور أو تعطيل حساب ووقت توقف الجلسات القائمة. لا تفترض أن تعديل سجل في قاعدة البيانات يبطل فوراً كل الرموز السابقة.")],
 [c("Logout, OTP, and device trust", "الخروج وOTP وثقة الأجهزة"), c("Local logout, identity-provider logout, and logout across applications are different events. Write down which sessions must end and how each application learns that change. For OTP, review expiry, attempt limits, and whether a code can be reused. For device trust, review how trust is granted and removed, and which actions still require stronger verification. These controls should have visible state transitions and audit events so a support investigation can explain an access decision.", "الخروج المحلي والخروج من مزود الهوية والخروج من جميع التطبيقات أحداث مختلفة. حدد الجلسات التي يجب إنهاؤها وكيف يصل التغيير لكل تطبيق. راجع مدة OTP وحدود المحاولات وإعادة استخدام الرمز. وبالنسبة لثقة الأجهزة، راجع منحها وإزالتها والإجراءات التي تتطلب تحققاً أقوى. يجب أن تتضمن الضوابط انتقالات واضحة وأحداث تدقيق تفسر قرارات الوصول.")],
 [c("A boundary-focused test matrix", "مصفوفة اختبار تركز على الحدود"), c("Use a matrix of identity state, application, role, resource owner, and expected decision. Include an expired token, an unexpected issuer or audience, a removed role, a disabled account, and a request for another tenant’s record. Repeat relevant cases through the API rather than relying only on hidden UI controls. The useful result is a reproducible explanation of why access was allowed or denied, including the stored state and the applicable policy.", "استخدم مصفوفة تشمل حالة الهوية والتطبيق والدور ومالك المورد والقرار المتوقع. ضمّن الرمز المنتهي والمصدر أو الجمهور الخاطئ والدور المحذوف والحساب المعطل وطلب سجل مؤسسة أخرى. كرر الحالات المناسبة عبر الواجهة البرمجية بدلاً من الاكتفاء بإخفاء أزرار الواجهة. النتيجة المفيدة تفسير قابل للتكرار لسبب السماح أو المنع مع الحالة المخزنة والسياسة المطبقة.")]
 ], references: [{ title: "Spring Security: JWT resource servers", url: "https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html" }] },
 "payment-integrations-state-transitions": {
 title: c("Designing Payment Integrations: State Machines, Webhooks & Safe Retries", "تصميم تكاملات الدفع: الحالات وWebhooks وإعادة المحاولة الآمنة"),
 flow: [c("Created", "منشأة"), c("Pending provider", "بانتظار المزود"), c("Confirmed / failed", "مؤكدة / فاشلة"), c("Reconciled record", "سجل مطابق")],
 sections: [
 [c("Define states before provider adapters", "حدد الحالات قبل موائمات المزود"), c("The flow above is illustrative: the exact states depend on whether the provider separates authorization and capture and on the product’s business rules. Start by naming confirmed states, transitional states, and unresolved states. Then map each provider response into that model. Keep external references and the internal operation identifier together. A provider adapter should translate a contract, while the application owns the business transition it permits.", "المسار أعلاه توضيحي؛ تعتمد الحالات الدقيقة على فصل المزود بين التفويض والتحصيل وقواعد المنتج. ابدأ بتسمية الحالات المؤكدة والانتقالية وغير المحسومة، ثم اربط استجابات المزود بها. احتفظ بالمعرف الخارجي ومعرف العملية الداخلي معاً. يترجم موائم المزود العقد بينما يملك التطبيق انتقال العمل المسموح.")],
 [c("Verify and record before acting", "تحقق وسجل قبل التنفيذ"), c("Stripe’s webhook guidance calls for signature verification using the raw request body and warns that events can be delivered more than once or out of order. That means a handler needs more than JSON parsing. After authenticity checks, decide whether the event has already been accepted and whether its transition is still applicable. Keep heavy processing out of the acknowledgement path when possible, while making the acceptance record durable enough to support recovery.", "توصي إرشادات Stripe بالتحقق من التوقيع باستخدام جسم الطلب الخام وتحذر من وصول الأحداث مكررة أو بترتيب مختلف. لذلك يحتاج المعالج إلى أكثر من تحليل JSON. بعد التحقق من الأصالة، حدد إن كان الحدث قد قُبل سابقاً وإن كان انتقاله لا يزال صالحاً. افصل المعالجة الثقيلة عن الإقرار قدر الإمكان مع حفظ سجل قبول دائم يدعم التعافي.")],
 [c("Reason about concurrent requests", "فهم الطلبات المتزامنة"), c("Imagine a customer retrying a checkout while a delayed webhook arrives. Both handlers may observe the same pending record. A read-then-write check alone can allow both to apply a side effect. Review the transaction boundary, uniqueness constraints, and conditional transition used to serialize that decision. The right mechanism depends on the data store, but the invariant is stable: one logical payment should not produce the same business effect twice.", "تخيل إعادة العميل محاولة الدفع أثناء وصول webhook متأخر. قد يرى المعالجان السجل المعلق نفسه. قد يسمح فحص القراءة ثم الكتابة لكليهما بتطبيق أثر العملية. راجع حدود المعاملة وقيود التفرد والانتقال المشروط الذي ينظم القرار. تختلف الآلية حسب التخزين، لكن القاعدة ثابتة: يجب ألا تكرر الدفعة المنطقية أثر العمل نفسه.")],
 [c("Reconciliation after an ambiguous result", "المطابقة بعد نتيجة غامضة"), c("When a request times out, preserve the distinction between no result and a confirmed failure. Reconciliation should use the provider’s supported lookup or event mechanism to resolve the operation. Define who owns that work and how unresolved records are surfaced for investigation. If retries are allowed, reuse the same logical operation identity according to the provider’s idempotency contract instead of creating an unrelated operation for every attempt.", "عند انتهاء المهلة، حافظ على الفرق بين غياب النتيجة والفشل المؤكد. استخدم آلية البحث أو الأحداث التي يدعمها المزود لحسم العملية. حدد المسؤول عن ذلك وكيف تظهر السجلات غير المحسومة للفحص. إذا سُمحت إعادة المحاولة، أعد استخدام هوية العملية المنطقية وفق عقد منع التكرار لدى المزود بدلاً من إنشاء عملية جديدة لكل محاولة.")],
 [c("Acceptance criteria that inspect business effects", "معايير قبول تفحص أثر العمل"), c("Test duplicate notifications, invalid signatures, delayed confirmation, a network interruption after provider acceptance, and competing updates. For each case, inspect both the transaction record and the business consequence, such as whether an order becomes eligible for fulfillment. A successful response code is insufficient if a duplicate action occurred. Keep test-provider data separate from real transactions and document the expected final state for every scenario.", "اختبر الإشعارات المكررة والتوقيعات غير الصالحة والتأكيد المتأخر وانقطاع الشبكة بعد قبول المزود والتحديثات المتنافسة. افحص سجل المعاملة وأثر العمل مثل أهلية الطلب للتنفيذ. لا تكفي استجابة ناجحة إذا تكرر الإجراء. افصل بيانات اختبار المزود عن المعاملات الحقيقية ووثق الحالة النهائية المتوقعة لكل سيناريو.")]
 ], references: [{ title: "Stripe: webhook delivery and signature verification", url: "https://docs.stripe.com/webhooks" }] },
 "laravel-performance-measure-before-caching": {
 title: c("Laravel Performance Engineering: Queries, Redis Caching & k6 Testing", "هندسة أداء Laravel: الاستعلامات وRedis واختبارات k6"),
 flow: [c("Baseline journey", "قياس الرحلة"), c("Profile bottleneck", "تحديد الاختناق"), c("Change one cause", "تغيير سبب واحد"), c("Repeat workload", "إعادة الحمل")],
 sections: [
 [c("Write a workload you can repeat", "اكتب حملاً يمكنك تكراره"), c("Define the endpoint mix, data volume, user concurrency or arrival rate, and test duration before comparing implementations. A tiny dataset may hide an expensive query; an unrealistic mix may overemphasize a rarely used route. Keep the environment, code revision, and cache state with the results. A baseline is useful when another run can reproduce its conditions, not simply when it produces a chart.", "حدد مزيج الواجهات وحجم البيانات والتزامن أو معدل الوصول ومدة الاختبار قبل المقارنة. قد تخفي البيانات الصغيرة استعلاماً مكلفاً أو يبالغ المزيج غير الواقعي في أهمية مسار نادر. احفظ البيئة وإصدار الكود وحالة الذاكرة المؤقتة مع النتائج. يفيد القياس الأساسي عندما يمكن إعادة إنتاج ظروفه لا لمجرد إنتاج رسم.")],
 [c("Look for repeated database work", "ابحث عن عمل قاعدة البيانات المتكرر"), c("Laravel’s Eloquent documentation explains how eager loading can reduce repeated relationship queries. Use query counts and traces to determine whether that pattern is relevant to the measured path. Loading every relationship is not the goal: inspect the fields and rows actually required by the response. Review pagination, filters, and indexes against the query plan, then verify that the returned records and ordering remain correct.", "تشرح وثائق Eloquent كيف يقلل التحميل المسبق استعلامات العلاقات المتكررة. استخدم عدد الاستعلامات والتتبع لتحديد صلة هذا النمط بالمسار المقاس. الهدف ليس تحميل كل العلاقات؛ بل فحص الحقول والصفوف المطلوبة فعلياً. راجع الصفحات والمرشحات والفهارس مقابل خطة الاستعلام ثم تحقق من صحة السجلات وترتيبها.")],
 [c("Design a cache as a consistency contract", "صمم التخزين المؤقت كعقد اتساق"), c("For each Redis-backed cache, name the source of truth, key scope, expiry, and invalidation trigger. Ask which stale values are tolerable and for how long. Shared data and tenant-specific data need different key boundaries. Also consider what happens when many requests encounter an expired entry together. The performance gain must be assessed alongside correctness and the additional work introduced by misses, refreshes, and invalidation.", "لكل ذاكرة مؤقتة تعتمد Redis، حدد مصدر الحقيقة ونطاق المفتاح والانتهاء وسبب الإبطال. اسأل عن القيم القديمة المقبولة ومدة قبولها. تحتاج البيانات المشتركة وبيانات المؤسسات إلى حدود مفاتيح مختلفة. افحص أيضاً وصول طلبات كثيرة إلى قيمة منتهية معاً. قيّم تحسن الأداء مع الصحة والعمل الإضافي الناتج عن الفقد والتجديد والإبطال.")],
 [c("Interpret latency together with errors", "فسر زمن الاستجابة مع الأخطاء"), c("An average can hide a slow tail, and a fast error response can make a failing system look quick. Inspect latency percentiles, throughput, and failures together. Separate application errors from test-environment limits. If the workload starts queuing, determine whether the limiting resource is the database, a worker pool, CPU, or a downstream dependency before changing configuration. One targeted hypothesis is easier to validate than several simultaneous optimizations.", "قد يخفي المتوسط طلبات بطيئة، وقد تجعل استجابة الخطأ السريعة نظاماً فاشلاً يبدو سريعاً. افحص مئينات الزمن والإنتاجية والأخطاء معاً. افصل أخطاء التطبيق عن قيود بيئة الاختبار. عند تراكم الطلبات، حدد المورد المقيد: قاعدة البيانات أو العمال أو المعالج أو خدمة لاحقة قبل تعديل الإعدادات. فرضية محددة أسهل تحققاً من تحسينات متزامنة عديدة.")],
 [c("Keep the optimization honest", "حافظ على دقة تقييم التحسين"), c("Pair the repeat load test with regression checks for the behavior changed by the optimization. For example, compare cached and uncached responses after a record update, and verify tenant separation. Store the before and after measurements with their conditions rather than reporting an unexplained percentage. My CV documents using query optimization, Redis, profiling, PHPUnit, and k6; project-specific benchmark results can be added when their measurement context is available.", "اربط اختبار الحمل المتكرر بفحوصات تراجع للسلوك المتغير. قارن مثلاً الاستجابات المخزنة وغير المخزنة بعد تحديث سجل وتحقق من فصل المؤسسات. احفظ قياسات قبل وبعد مع ظروفها بدلاً من نسبة بلا تفسير. توثق سيرتي استخدام تحسين الاستعلامات وRedis والتحليل وPHPUnit وk6، ويمكن إضافة نتائج خاصة بالمشاريع عند توفر سياق قياسها.")]
 ], references: [{ title: "Laravel: Eloquent eager loading", url: "https://laravel.com/docs/12.x/eloquent-relationships#eager-loading" }] },
};
