import { experiencePosts } from "./experience-posts";
export type Copy = { en: string; ar: string };
const copy = (en: string, ar: string): Copy => ({ en, ar });
export const sections = {
 expertise: { title: copy("Expertise", "الخبرات التقنية"), intro: copy("Engineering from the first API contract to the final release check.", "هندسة تبدأ من تصميم واجهات البرمجة وتستمر حتى التحقق من جاهزية الإصدار."), details: [
  [copy("Start with the contract", "البداية من العقد"), copy("Define inputs, permissions, validation rules, and failure responses before connecting services. Clear boundaries make backend behavior easier to implement, test, and maintain.", "تحديد المدخلات والصلاحيات وقواعد التحقق واستجابات الأخطاء قبل ربط الخدمات يجعل سلوك النظام أوضح وأسهل في التطوير والاختبار والصيانة.")],
  [copy("Test beyond the happy path", "اختبار ما وراء المسار المثالي"), copy("Combine API checks, browser automation, exploratory testing, and load testing. Give authentication, payment transitions, and data integrity particular attention because failures there affect the whole product.", "الجمع بين اختبار الواجهات وأتمتة المتصفح والاختبار الاستكشافي واختبار الحمل، مع الاهتمام بالمصادقة وانتقالات الدفع وسلامة البيانات لتأثيرها على المنتج بأكمله.")],
  [copy("Carry quality into delivery", "الجودة حتى التسليم"), copy("Connect automated checks with delivery pipelines, then use logs and production troubleshooting to understand behavior in real environments. Reliability depends on the operating system as much as the application code.", "ربط الفحوصات الآلية بمسارات التسليم واستخدام السجلات وتشخيص مشاكل الإنتاج لفهم السلوك الفعلي. تعتمد الموثوقية على بيئة التشغيل بقدر اعتمادها على الكود.")]
 ]},
 experience: { title: copy("Experience", "الخبرة المهنية"), intro: copy("A career connecting software development, quality assurance, and technical leadership.", "مسيرة تجمع بين تطوير البرمجيات وضمان الجودة والقيادة التقنية."), details: [
  [copy("A foundation in validation", "أساس في التحقق"), copy("At ecmarkt.com, API and interface testing connected business requirements with observable behavior. Reproducible defect reports and verification of fixes were central to that work.", "في ecmarkt.com، ربط اختبار الواجهات ومتطلبات العمل بالسلوك الفعلي للمنتج، مع التركيز على توثيق العيوب القابلة لإعادة الإنتاج والتحقق من إصلاحها.")],
  [copy("Building connected services", "بناء خدمات مترابطة"), copy("At Prokoders, the focus expanded into Laravel applications and Java services. The Laravel and Spring roles overlapped, linking support workflows with shared identity, payment integrations, and real-time events.", "في Prokoders، توسع العمل إلى تطبيقات Laravel وخدمات Java. تداخل الدوران لربط الدعم بالهوية المشتركة وتكاملات الدفع والأحداث اللحظية.")],
  [copy("Making release risk visible", "توضيح مخاطر الإصدار"), copy("QA management at IXCoders brings functional, integration, performance, and security testing together. The responsibility includes coordinating remediation and communicating release readiness to stakeholders.", "تجمع إدارة الجودة في IXCoders بين الاختبارات الوظيفية والتكامل والأداء والأمان، وتشمل تنسيق الإصلاحات وإبلاغ المعنيين بجاهزية الإصدار.")]
 ]},
 work: { title: copy("Selected work", "أعمال مختارة"), intro: copy("A closer look at the systems, responsibilities, and technical decisions behind the portfolio.", "نظرة أعمق على الأنظمة والمسؤوليات والقرارات التقنية وراء هذه الأعمال."), details: [
  [copy("CallX · service boundaries", "CallX · حدود الخدمات"), copy("Calling and core business operations have separate backends. This separates live communication concerns from tenant management, CRM, and HR while keeping a shared service-token contract between them. CallX remains in active development.", "تعمل المكالمات والعمليات الأساسية في خدمتين منفصلتين لفصل الاتصال اللحظي عن إدارة المؤسسات والعملاء والموارد البشرية، مع عقد مشترك لرموز الخدمات. لا يزال CallX قيد التطوير.")],
  [copy("Britrip · connected workflows", "Britrip · مسارات مترابطة"), copy("The contribution spans Spring Boot SSO and payment services alongside Laravel support and ticketing. Kafka events and WebSocket notifications connect platform activity; other Laravel developers integrated their services with the shared SSO.", "تشمل المساهمة خدمات الدخول الموحد والدفع باستخدام Spring Boot والدعم والتذاكر باستخدام Laravel. تربط أحداث Kafka وإشعارات WebSocket نشاط المنصة، وقد ربط مطورو Laravel الآخرون خدماتهم بالدخول الموحد.")],
  [copy("Business systems · validation scope", "أنظمة الأعمال · نطاق التحقق"), copy("ERP, CRM, HR, and commerce projects bring different risks: business-rule consistency, branch-level workflows, customer records, and order integrity. The QA work focuses on those journeys and their data, with each project’s role identified below.", "تطرح مشاريع ERP وCRM والموارد البشرية والتجارة مخاطر مختلفة تتعلق بقواعد العمل والفروع وسجلات العملاء وسلامة الطلبات. يركز ضمان الجودة على هذه المسارات وبياناتها، مع توضيح الدور في كل مشروع أدناه.")]
 ]},
 about: { title: copy("About me", "نبذة عني"), intro: copy("Software engineering with curiosity, clear communication, and care for the details.", "هندسة برمجيات تقوم على الفضول والتواصل الواضح والاهتمام بالتفاصيل."), details: [
  [copy("An engineering perspective", "منظور هندسي"), copy("Working on both implementation and validation connects two useful questions: how should this system work, and how could it fail? That perspective informs API design, integration work, and release testing.", "يجمع العمل في التطوير والتحقق بين سؤالين: كيف ينبغي أن يعمل النظام، وكيف يمكن أن يفشل؟ يوجّه هذا المنظور تصميم الواجهات والتكامل واختبارات الإصدار.")],
  [copy("Learning and community", "التعلم والمجتمع"), copy("A Computer Science degree at Damascus University and volunteering with RBCs Team both ran from 2020 to 2025. The portfolio brings that foundation together with practical experience across backend development and quality engineering.", "امتدت دراسة علوم الحاسوب في جامعة دمشق والتطوع مع فريق RBCs من 2020 إلى 2025. تجمع هذه الأعمال بين هذا الأساس والخبرة العملية في تطوير الخدمات الخلفية وهندسة الجودة.")],
  [copy("Working across disciplines", "التعاون بين التخصصات"), copy("Backend services rarely exist in isolation. Clear requirements, reproducible findings, and communication with developers and stakeholders help connect technical decisions to the people using the product.", "نادراً ما تعمل الخدمات الخلفية بمعزل عن غيرها. تساعد المتطلبات الواضحة والنتائج القابلة لإعادة الإنتاج والتواصل مع المطورين والمعنيين على ربط القرارات التقنية بمستخدمي المنتج.")]
 ]},
 contact: { title: copy("Let’s talk", "لنتحدث"), intro: copy("Have a backend challenge, a quality initiative, or an engineering role in mind? Start a conversation.", "هل لديك تحدٍّ في الخدمات الخلفية أو مبادرة جودة أو فرصة هندسية؟ لنتحدث."), details: [
  [copy("Project conversations", "مناقشة المشاريع"), copy("Share what you are building, your current stack, and the main challenge. A short description of the existing system helps establish the right technical context.", "شارك فكرة مشروعك والتقنيات الحالية والتحدي الأساسي. يساعد وصف موجز للنظام الموجود على تحديد السياق التقني المناسب.")],
  [copy("Roles and collaboration", "الفرص والتعاون"), copy("For engineering or quality roles, include the responsibilities, team setup, location or remote expectations, and hiring timeline. The downloadable CV provides a fuller overview of experience.", "لفرص الهندسة أو الجودة، يرجى ذكر المسؤوليات وطبيعة الفريق والموقع أو متطلبات العمل عن بعد والجدول الزمني للتوظيف. تتضمن السيرة الذاتية تفاصيل أوسع عن الخبرة.")],
  [copy("A useful first message", "رسالة أولى مفيدة"), copy("Include the goal, scope, expected timing, and any constraints you already know. Email is a direct way to share those details; references are available on request.", "اذكر الهدف والنطاق والوقت المتوقع وأي قيود معروفة. البريد الإلكتروني وسيلة مباشرة لمشاركة هذه التفاصيل، والمراجع متاحة عند الطلب.")]
 ]},
};
export type SectionKey = keyof typeof sections;
export const posts = [
 ...experiencePosts,
 { slug: "designing-reliable-api-contracts", category: copy("Backend engineering", "هندسة الخدمات الخلفية"), title: copy("Reliable APIs start with clear contracts", "واجهات موثوقة تبدأ بعقود واضحة"), summary: copy("Inputs, permissions, and failure states deserve as much attention as successful responses.", "تستحق المدخلات والصلاحيات وحالات الفشل اهتماماً يوازي الاستجابات الناجحة."), body: [
 [copy("Define behavior before implementation", "تحديد السلوك قبل التنفيذ"), copy("An endpoint is a promise to its callers. Before choosing a controller or database query, describe the resource, required fields, and valid state transitions. Consider a support ticket: creating it, assigning it, and closing it are different actions with different preconditions. Making those differences explicit keeps clients from guessing what the server will accept.", "واجهة البرمجة وعد لمستخدميها. قبل اختيار المتحكم أو استعلام قاعدة البيانات، حدد المورد والحقول المطلوبة وانتقالات الحالة الصحيحة. إنشاء تذكرة دعم وتعيينها وإغلاقها إجراءات مختلفة بشروط مختلفة. توضيح هذه الفروق يمنع التطبيقات المستهلكة من تخمين ما يقبله الخادم.")],
 [copy("Treat permissions as part of the contract", "الصلاحيات جزء من العقد"), copy("Authentication establishes an identity; authorization decides whether that identity can perform an action on a particular resource. For a multi-tenant service, checking a role alone is insufficient. A request must also be scoped to the appropriate tenant and resource. Tests should include a valid user attempting to access another tenant’s record, not just requests without credentials.", "تثبت المصادقة الهوية، بينما يقرر التفويض إن كان يحق لها تنفيذ إجراء على مورد معين. في الخدمات متعددة المؤسسات، لا يكفي التحقق من الدور وحده؛ بل يجب تقييد الطلب بالمؤسسة والمورد المناسبين. ينبغي اختبار مستخدم صحيح يحاول الوصول إلى سجل مؤسسة أخرى، وليس الطلبات بلا بيانات دخول فقط.")],
 [copy("Make failures predictable", "جعل الفشل قابلاً للتوقع"), copy("Clients need a stable way to distinguish invalid input, denied access, missing resources, and temporary service failures. Keep error codes and response shapes consistent, and avoid leaking internal exception details. When a request times out, the caller may not know whether it succeeded. For operations with side effects, define retry behavior and an idempotency strategy before encouraging automatic retries.", "تحتاج التطبيقات إلى تمييز ثابت بين المدخلات غير الصالحة ومنع الوصول والموارد المفقودة وأعطال الخدمة المؤقتة. حافظ على اتساق رموز الأخطاء وبنية الاستجابة دون كشف تفاصيل الاستثناءات الداخلية. عند انتهاء مهلة الطلب، قد لا يعرف العميل إن نجحت العملية؛ لذا يجب تحديد سلوك إعادة المحاولة ومنع تكرار الأثر قبل أتمتة المحاولات.")],
 [copy("Turn the contract into checks", "تحويل العقد إلى فحوصات"), copy("A practical review includes one successful request, boundary values, missing fields, incorrect permissions, and repeated requests. Verify both the response and the stored state. An API can return the expected status while leaving incorrect data behind. Contract tests become most useful when they protect behavior that other services actually depend on.", "تشمل المراجعة العملية طلباً ناجحاً وقيم الحدود والحقول المفقودة والصلاحيات الخاطئة والطلبات المتكررة. تحقق من الاستجابة والبيانات المخزنة معاً؛ فقد تعيد الواجهة الحالة المتوقعة وتترك بيانات خاطئة. تصبح اختبارات العقود أكثر فائدة عندما تحمي سلوكاً تعتمد عليه خدمات أخرى فعلياً.")]
 ]},
 { slug: "testing-beyond-the-happy-path", category: copy("Quality engineering", "هندسة الجودة"), title: copy("Test the journey, including the detours", "اختبر الرحلة بما فيها المسارات غير المتوقعة"), summary: copy("A practical way to turn business risks into a focused test strategy.", "طريقة عملية لتحويل مخاطر الأعمال إلى استراتيجية اختبار مركزة."), body: [
 [copy("Start with what could hurt", "البداية من المخاطر المؤثرة"), copy("A long test checklist is not automatically a useful strategy. Begin with the actions that matter to users: signing in, placing an order, changing a record, or completing a payment. Ask what failure would mean for each journey. Lost data, unauthorized access, and duplicate charges deserve different attention from a cosmetic alignment issue.", "قائمة اختبار طويلة ليست بالضرورة استراتيجية مفيدة. ابدأ بالإجراءات المهمة للمستخدم: تسجيل الدخول أو تقديم طلب أو تعديل سجل أو إتمام دفعة. اسأل عن أثر فشل كل رحلة؛ فضياع البيانات والوصول غير المصرح والرسوم المتكررة تستحق اهتماماً مختلفاً عن مشكلة تنسيق بسيطة.")],
 [copy("Follow the state, not only the screen", "تتبع الحالة وليس الشاشة فقط"), copy("A success message is only one observation. For an order workflow, inspect whether the order was persisted correctly, whether inventory changed as expected, and whether a failed payment leaves a recoverable state. Test interrupted requests and repeated submissions. These checks connect the visible interface with the business rules behind it.", "رسالة النجاح ملاحظة واحدة فقط. في مسار الطلب، تحقق من حفظه وتغير المخزون كما هو متوقع وبقاء حالة قابلة للاستعادة عند فشل الدفع. اختبر الطلبات المنقطعة والإرسال المتكرر. تربط هذه الفحوصات الواجهة المرئية بقواعد العمل خلفها.")],
 [copy("Choose the right layer", "اختيار طبقة الاختبار المناسبة"), copy("Use focused unit tests for isolated rules, API tests for service behavior, and browser tests for critical end-to-end journeys. Browser automation is valuable, but repeating every variation through the UI makes suites slow and harder to diagnose. Exploratory sessions complement automation by questioning assumptions the scripts already take for granted.", "استخدم اختبارات الوحدة للقواعد المنفصلة واختبارات API لسلوك الخدمات واختبارات المتصفح للرحلات الأساسية الكاملة. أتمتة المتصفح مهمة، لكن تكرار كل حالة عبر الواجهة يبطئ الاختبارات ويصعّب التشخيص. يكمل الاختبار الاستكشافي الأتمتة بمراجعة افتراضات تتعامل معها البرامج النصية كحقائق.")],
 [copy("Communicate the remaining risk", "توضيح المخاطر المتبقية"), copy("A release summary should explain what was tested, what was not, which defects remain, and the likely user impact. A passing suite is evidence within a defined scope, not a guarantee of perfection. Clear reporting helps the team make an informed release decision and identify what to monitor afterward.", "يجب أن يوضح تقرير الإصدار ما اختُبر وما لم يُختبر والعيوب المتبقية وأثرها المحتمل. نجاح الاختبارات دليل ضمن نطاق محدد وليس ضماناً للكمال. تساعد التقارير الواضحة الفريق على اتخاذ قرار إصدار واعٍ وتحديد ما يجب مراقبته لاحقاً.")]
 ]},
 { slug: "real-time-systems-and-recovery", category: copy("System design", "تصميم الأنظمة"), title: copy("Real-time systems need a recovery story", "الأنظمة اللحظية تحتاج خطة للتعافي"), summary: copy("Connections drop. Events repeat. Design the path back to a consistent state.", "تنقطع الاتصالات وتتكرر الأحداث. صمّم مسار العودة إلى حالة متسقة."), body: [
 [copy("A connection is not the source of truth", "الاتصال ليس مصدر الحقيقة"), copy("A WebSocket can deliver changes quickly, but the connection itself should not be the only record of what happened. A client may disconnect while an important update is sent. Keep durable business state in the backend and provide a way to read it again. Live messages then improve responsiveness without becoming the sole means of reconstructing the user’s view.", "يمكن لـ WebSocket إيصال التغييرات بسرعة، لكن الاتصال نفسه يجب ألا يكون السجل الوحيد للأحداث. قد ينقطع العميل عند إرسال تحديث مهم. احتفظ بحالة الأعمال الدائمة في الخادم ووفر وسيلة لإعادة قراءتها. تحسن الرسائل اللحظية سرعة الاستجابة دون أن تكون الوسيلة الوحيدة لإعادة بناء واجهة المستخدم.")],
 [copy("Expect repetition and reordering", "توقع التكرار وتغير الترتيب"), copy("Retries can cause the same event to be processed more than once. Multiple producers can also introduce ordering surprises. Give events stable identifiers and make consumers tolerate duplicates. When order matters for one entity, use an explicit version or sequence and define what should happen when a consumer sees an older update after a newer one.", "قد تؤدي إعادة المحاولة إلى معالجة الحدث أكثر من مرة، وقد يتغير ترتيب الأحداث مع تعدد المنتجين. أعطِ الأحداث معرفات ثابتة واجعل المستهلك يتحمل التكرار. عندما يهم ترتيب أحداث كيان واحد، استخدم إصداراً أو تسلسلاً واضحاً وحدد كيفية التعامل مع تحديث قديم يصل بعد تحديث أحدث.")],
 [copy("Reconnect deliberately", "إعادة الاتصال بخطة واضحة"), copy("After a disconnect, retry with backoff and jitter so clients do not all reconnect at once. Once connected, reconcile the visible state using a snapshot or a supported replay mechanism. Be explicit about what the user sees while the state is uncertain. A reconnecting indicator is more honest than presenting an old queue or presence status as current.", "بعد الانقطاع، أعد المحاولة بتأخير متزايد وعشوائية بسيطة لتجنب عودة جميع العملاء دفعة واحدة. بعد الاتصال، طابق الحالة المرئية مع لقطة حديثة أو آلية لإعادة الأحداث. وضح للمستخدم أن الحالة غير مؤكدة؛ فمؤشر إعادة الاتصال أدق من عرض طابور أو حالة حضور قديمة على أنها حديثة.")],
 [copy("Test recovery as a feature", "اختبار التعافي كميزة"), copy("Disconnect a client, restart a consumer, delay an event, and deliver a duplicate. Check whether the system returns to a consistent state without creating duplicate business actions. Measure recovery time as well as steady-state latency. A real-time experience is only dependable when the recovery path receives the same attention as the live path.", "اقطع اتصال العميل وأعد تشغيل المستهلك وأخّر حدثاً وأرسل نسخة مكررة. تحقق من عودة النظام لحالة متسقة دون تكرار إجراءات العمل. قِس وقت التعافي إلى جانب زمن الاستجابة المعتاد. تعتمد موثوقية التجربة اللحظية على منح مسار التعافي اهتماماً يوازي المسار المباشر.")]
 ]},
];
